spring:
  datasource:
    url: jdbc:postgresql://118.25.193.38:443/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8